name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          labels: |
            ryan
            bug

  build-zero:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: windows-latest
    steps:
      - name: show OS
        run: echo "windows"

  build:
    if: ${{ github.event.label.name != 'bug' }}
    runs-on: ubuntu-latest
    steps:
      - name: show OS
        run: echo "ubuntu"